import os


USING_COLAB = False

IMG_WIDTH = 128
IMG_HEIGHT = 64

PATH_PREFIX = ''
if USING_COLAB:
    PATH_PREFIX = 'drive/ANPR/'

MODEL_PATH = PATH_PREFIX + 'data/boundingbox'
SAMPLES_PATHS = [PATH_PREFIX + 'data/boundingbox/j__artificial']

BATCH_SIZE = 20

EPOCH = 90

THREE_DIGITS_THRESHOLD = 0.3
GAUSS_FILTER_SIGMA = 1
REGION_MIN_VALUE = -0.01
REGION_MAX_VALUE = 0.2
REGION_THRESHOLD = 0.35
REGION_STRIDE = 1
MERGE_STRIDE = 3
LIGHT_THRESHOLD = 0.3
DARK_THRESHOLD = 0.1
FILL_THRESHOLD = 0.65
IGNORE_THRESHOLD = 0.25
ROI_LIGHT_THRESHOLD = 0.55
ROI_AVG_THRESHOLD = 0.5

if not os.path.exists(MODEL_PATH):
    os.makedirs(MODEL_PATH)